STATUS_CLASSES = {
    "en cours": "st-en-cours",
    "en pause": "st-en-pause",
    "terminé": "st-termine",
    "planifié": "st-planifie",
    "abandonné": "st-abandonne",
}


def css_class_for_status(status: str) -> str:
    return STATUS_CLASSES.get(status, "st-planifie")


THEMES = {
    "Dark": {
        "bg": "#0e0e10",
        "text": "#fafafa",
        "accent": "#05bad6",
        "box_bg": "#18181b",
        "box_border": "#27272a",
        "subtitle": "#71717a",
        "error_border": "#3f1a1a",
        "error_text": "#ef4343",
        "doc_bg": "#0a1a12",
        "doc_border": "#1a3a2a",
        "doc_text": "#05bad6",
        "status_plan": "#18181b",
        "status_plan_text": "#71717a",
        "status_en_cours": "#0a2a1a",
        "status_en_cours_text": "#05bad6",
        "status_pause": "#2a2a0a",
        "status_pause_text": "#cfcf6f",
        "status_termine": "#0a1a2a",
        "status_termine_text": "#05bad6",
        "status_abandon": "#2a0a0a",
        "status_abandon_text": "#ef4343",
    },
    "WhiteBullet": {
        "bg": "#0e0e14",
        "text": "#e0dfff",
        "accent": "#ab8bff",
        "box_bg": "#16162a",
        "box_border": "#2a2a4a",
        "subtitle": "#6a6a8a",
        "error_border": "#4a1a3a",
        "error_text": "#ff6b9d",
        "doc_bg": "#1a1a3a",
        "doc_border": "#3a3a6a",
        "doc_text": "#ab8bff",
        "status_plan": "#1a1a2a",
        "status_plan_text": "#6a6a8a",
        "status_en_cours": "#1a2a3a",
        "status_en_cours_text": "#8bafff",
        "status_pause": "#3a2a1a",
        "status_pause_text": "#cfaf6f",
        "status_termine": "#1a1a3a",
        "status_termine_text": "#ab8bff",
        "status_abandon": "#3a1a2a",
        "status_abandon_text": "#ff6b9d",
    },
    "Cyan": {
        "bg": "#0a1212",
        "text": "#d0eeee",
        "accent": "#22d3ee",
        "box_bg": "#0f1a1a",
        "box_border": "#1a2e2e",
        "subtitle": "#4a7a7a",
        "error_border": "#3a1a1a",
        "error_text": "#e06c75",
        "doc_bg": "#0f2a1a",
        "doc_border": "#1a4a2a",
        "doc_text": "#4ae09a",
        "status_plan": "#0f1a1a",
        "status_plan_text": "#4a7a7a",
        "status_en_cours": "#0f2a1a",
        "status_en_cours_text": "#4ae09a",
        "status_pause": "#2a2a0f",
        "status_pause_text": "#c0c040",
        "status_termine": "#0f1a2a",
        "status_termine_text": "#22d3ee",
        "status_abandon": "#2a1a0f",
        "status_abandon_text": "#e06c75",
    },
    "Light": {
        "bg": "#f5f5f5",
        "text": "#1a1a1a",
        "accent": "#6366f1",
        "box_bg": "#eee",
        "box_border": "#ddd",
        "subtitle": "#888",
        "error_border": "#fcc",
        "error_text": "#d32f2f",
        "doc_bg": "#e8f5e9",
        "doc_border": "#a5d6a7",
        "doc_text": "#2e7d32",
        "status_plan": "#e0e0e0",
        "status_plan_text": "#666",
        "status_en_cours": "#c8e6c9",
        "status_en_cours_text": "#2e7d32",
        "status_pause": "#fff9c4",
        "status_pause_text": "#f57f17",
        "status_termine": "#c5cae9",
        "status_termine_text": "#283593",
        "status_abandon": "#ffcdd2",
        "status_abandon_text": "#c62828",
    },
}
